### PR TITLE
Set  RVConnectionData time as DateTime

### PR DESCRIPTION
**Pull request by DaniElectra**
~~Set the structure version to 1 if NEX version is 3.5+~~

### CODE REVIEW

**Comment by jonbarrow** [comment]
Why is this being done in this library? This feels like something `nex-go` should handle when encoding the data in the stream

**Comment by DaniElectra** [comment]
We can't set the version on `nex-go` because by the time we get to `RVConnectionData.Bytes()` the structure version is already written in the stream. Unless we set the structure version when creating the structure?

**Comment by DaniElectra** [comment]
Actually no, my bad. I was thinking that the version was written before calling `Structure.Bytes()`

~~Should I close this PR or wait for updating the modules?~~ I actually have to update the time value for `RVConnectionData` anyway

**Comment by jonbarrow** [comment]
Is this good to close then?

**Comment by DaniElectra** [comment]
No, I will use this PR to update the time for `RVConnectionData` from uint64 to a DateTime

*sorry about this confusion lmao*

**Pull request merged**
